### ISSUE TITLE
uprage to python 3.10?

### ISSUE THREAD

**Issue by SXDOW** [CybernetiX-S3C/InfoSploit#3]
i have python2 and 3 but i cant use pip install it would be nice if you use python3 for that script

but its very very nice

**Comment by CybernetiX-S3C** [comment]
It runs on most pythons. Run the installer and then call it as mentioned.

If you are having issues with pip, make sure you try calling it properly.


python2 -m pip install packagename

python3 -m pip install packagename

pip2 install packagename

pip3 install packagename

Sorry for the delay... 😊
